-- MySQL
show databases; -- Lista os bancos de dados.
show tables; -- Lista as tabelas.
use db_teste; -- Seleciona um banco de dados.

-- PostgreSQL
\l -- Lista os bancos de dados
\c db_name -- Seleciona um banco de dados.
\dt -- Lista as tabelas
psql -U postgres -- Entra como usuário padrão.

-- SQL
CREATE TABLE table_name ( -- Cria uma tabela
    column1 datatype [constraints],
    column2 datatype [constraints],
    column3 datatype [constraints],
    ...
);

ALTER TABLE table_name ADD column_name datatype [constraints]; -- Adiciona uma coluna na tabela.
ALTER TABLE table_name ADD PRIMARY KEY (column_name); -- Adiciona uma Primary Key na tabela.
ALTER TABLE table_name ALTER COLUMN column_name ADD GENERATED BY DEFAULT AS IDENTITY; -- Informa que uma coluna da tabela possui autoincremento.
SELECT create_hypertable('table_name', 'column_name'); -- Cria uma hypertable com uma coluna de tempo específica.
DROP TABLE table_name; -- Apaga a tabela.

INSERT INTO table_name (column1, column2, column3, ...) VALUES (value1, value2, value3, ...); -- Insere dados.

UPDATE table_name SET column_name2=value2, column_name3=value3 WHERE column_name1=value1; -- Atualiza dados.

SELECT coluna FROM tabela WHERE condicao ORDER BY nome ASC GROUP BY idade ASC; -- Seleciona dados com ORDER BY e GROUP BY.
SELECT * FROM table_name1 INNER JOIN table_name2 ON table_name1.column_name1 = table_name2.column_name2; -- Seleciona dados com INNER JOIN.