-- MySQL Script generated by MySQL Workbench
-- 05/08/17 16:08:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_gabriel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_gabriel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_gabriel` DEFAULT CHARACTER SET utf8 ;
USE `db_gabriel` ;

-- -----------------------------------------------------
-- Table `db_gabriel`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gabriel`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(85) NOT NULL,
  `email` VARCHAR(85) NOT NULL,
  `senha` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_gabriel`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gabriel`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(85) NOT NULL,
  `url` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_gabriel`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gabriel`.`noticia` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `titulo` VARCHAR(85) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `img` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id_noticia`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_gabriel`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gabriel`.`contato` (
  `id_contato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(85) NOT NULL,
  `email` VARCHAR(85) NOT NULL,
  `assunto` VARCHAR(85) NULL,
  `mensagem` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id_contato`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
