-- MySQL Script generated by MySQL Workbench
-- 11/10/17 21:10:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_14news
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_14news
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_14news` DEFAULT CHARACTER SET utf8 ;
USE `db_14news` ;

-- -----------------------------------------------------
-- Table `db_14news`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_14news`.`noticias` (
  `id_noticias` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `data` DATE NOT NULL,
  `corpo` LONGTEXT NOT NULL,
  `imgs` LONGTEXT NULL,
  PRIMARY KEY (`id_noticias`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_14news`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_14news`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = MyISAM;

USE `db_14news` ;

-- -----------------------------------------------------
-- Placeholder table for view `db_14news`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_14news`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `db_14news`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_14news`.`view1`;
USE `db_14news`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
