-- MySQL Script generated by MySQL Workbench
-- 08/02/17 19:04:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_library` DEFAULT CHARACTER SET utf8 ;
USE `db_library` ;

-- -----------------------------------------------------
-- Table `db_library`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `autor` VARCHAR(80) NOT NULL,
  `ano` YEAR NOT NULL,
  `tag` SET('anime', 'filme', 'jogo', 'livro', 'novela', 'série') NOT NULL,
  `all_episodes` DECIMAL(10,0) NULL,
  `atual_episode` DECIMAL(10,0) NULL,
  `estado` VARCHAR(80) NULL,
  `ovas` DECIMAL(10,0) NULL,
  `filmes` DECIMAL(10,0) NULL,
  `sinopse` LONGTEXT NOT NULL,
  `img` VARCHAR(80) NOT NULL,
  `elenco` LONGTEXT NULL,
  `atual_season` DECIMAL(10,0) NULL,
  `categoria` VARCHAR(80) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_library`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_library`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`noticia` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(80) NOT NULL,
  `img` VARCHAR(80) NULL,
  `descricao` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_noticia`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
