-- MySQL Script generated by MySQL Workbench
-- 07/23/17 13:56:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_library` DEFAULT CHARACTER SET utf8 ;
USE `db_library` ;

-- -----------------------------------------------------
-- Table `db_library`.`animes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`animes` (
  `id_animes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `autor` VARCHAR(80) NOT NULL,
  `ano` YEAR NOT NULL,
  `categoria` VARCHAR(80) NOT NULL,
  `all_episodes` DECIMAL(10,0) NOT NULL,
  `atual_episode` DECIMAL(10,0) NOT NULL,
  `estado` VARCHAR(80) NOT NULL,
  `ovas` DECIMAL(10,0) NOT NULL,
  `filmes` DECIMAL(10,0) NOT NULL,
  `sinopse` LONGTEXT NOT NULL,
  `img` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_animes`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_library`.`filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`filmes` (
  `id_filmes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `diretor` VARCHAR(80) NOT NULL,
  `ano` YEAR NOT NULL,
  `categoria` VARCHAR(80) NOT NULL,
  `elenco` LONGTEXT NOT NULL,
  `sinopse` LONGTEXT NOT NULL,
  `img` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_filmes`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_library`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`jogos` (
  `id_jogos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `desenvolvedor` VARCHAR(80) NOT NULL,
  `ano` YEAR NOT NULL,
  `categoria` VARCHAR(80) NOT NULL,
  `sinopse` LONGTEXT NOT NULL,
  `img` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_jogos`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_library`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`livros` (
  `id_livros` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `autor` VARCHAR(80) NOT NULL,
  `ano` YEAR NOT NULL,
  `categoria` VARCHAR(80) NOT NULL,
  `personagens` LONGTEXT NOT NULL,
  `sinopse` LONGTEXT NOT NULL,
  `img` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_livros`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_library`.`novelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`novelas` (
  `id_novelas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `diretor` VARCHAR(80) NOT NULL,
  `ano` VARCHAR(80) NOT NULL,
  `categoria` VARCHAR(80) NOT NULL,
  `elenco` VARCHAR(80) NOT NULL,
  `capitulo` DECIMAL(10,0) NOT NULL,
  `sinopse` LONGTEXT NOT NULL,
  `img` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_novelas`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_library`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`series` (
  `id_series` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `diretor` VARCHAR(80) NOT NULL,
  `ano` YEAR NOT NULL,
  `categoria` VARCHAR(80) NOT NULL,
  `elenco` LONGTEXT NOT NULL,
  `atual_season` DECIMAL(10,0) NOT NULL,
  `atual_episode` DECIMAL(10,0) NOT NULL,
  `estado` VARCHAR(80) NOT NULL,
  `sinopse` LONGTEXT NOT NULL,
  `img` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_series`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_library`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_library`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`noticia` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(80) NOT NULL,
  `img` VARCHAR(80) NULL,
  `descricao` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_noticia`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
