-- MySQL Script generated by MySQL Workbench
-- 06/03/17 15:41:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_tecflix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_tecflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tecflix` DEFAULT CHARACTER SET utf8 ;
USE `db_tecflix` ;

-- -----------------------------------------------------
-- Table `db_tecflix`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tecflix`.`series` (
  `id_series` INT NOT NULL AUTO_INCREMENT,
  `img` VARCHAR(85) NOT NULL,
  `nome` VARCHAR(85) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `ano` YEAR NOT NULL,
  `diretor` VARCHAR(85) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `categoria` VARCHAR(85) NOT NULL,
  `categoria2` VARCHAR(85) NULL,
  PRIMARY KEY (`id_series`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_tecflix`.`contribua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tecflix`.`contribua` (
  `id_contribua` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(85) NOT NULL,
  `serie` VARCHAR(85) NOT NULL,
  `comentario` LONGTEXT NULL,
  PRIMARY KEY (`id_contribua`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
